name: 'Build and publish'

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[p skip]') }}
    steps:
      - name: 'Validate repository'
        uses: actions/checkout@v1

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 'Install dependencies'
        run: npm ci

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
